### ISSUE TITLE
Incorrect positioning arrows image, it overlap all form 

### ISSUE THREAD

**Issue by Insolita** [GuillaumeFerron/post-content#1]
Bug Description (required)
----------------------------
Incorrect positioning arrows image, it overlap all form, Screenshot attached

- Laravel Nova version - 1.2.1
- Laravel version 5.7.19
- Browser - Firefox 64.0

Where ? (required)
-----------------
- [ ] Detail
- [ x] Form
- [ ] Index
- [ ] Other: ...

To Reproduce
--------------
1. Just install extension
2. Use it in Resource as `PostContent::make('Content', 'content_raw')->hideFromIndex(),`

Screenshots
-----------
![contentbug](https://user-images.githubusercontent.com/1847402/50409830-7d96d480-0830-11e9-8cc5-7d58b4970c02.png)
 

Additional Comments
-------------------
I also check it without any other fields and with default nova theme, for ensure, that is not conflict bug

**Comment by GuillaumeFerron** [comment]
Hi @Insolita,

I know it's been an eternity, just got around working on that package again. Hope it might still be of use to you, if not might be for someone else.

I never really got your issue, most likely coming from a different styling rule that you would have in your project.

I pushed a version v1.1.0 that should make sure the arrows icon is properly sized.

https://github.com/GuillaumeFerron/post-content/releases/tag/1.1.0

Let me know if that worked for you.

Closing this issue
