### ISSUE TITLE
Make "hardcoded" strings translatable

### ISSUE THREAD

**Issue by michielabe** [GuillaumeFerron/post-content#2]
Hey l really like your package but can you make the strings translatable using localization from laravel?

**Comment by GuillaumeFerron** [comment]
Hi @michielabe,

First thank you for the feedback, appreciate it.

I know it's been an eternity, just got around working on that package again. Hope it might still be of use to you, if not might be for someone else.

I pushed a version v1.1.0 that should take care of using the Laravel Nova localization structure (https://nova.laravel.com/docs/3.0/customization/localization.html).

https://github.com/GuillaumeFerron/post-content/releases/tag/1.1.0

Let me know if that worked for you.

Closing this issue
