### ISSUE TITLE
First row is always text

### ISSUE THREAD

**Issue by Muetze42** [GuillaumeFerron/post-content#5]
With this option:
`->withFields(['image', 'video'])`

The first row is always text.

**Comment by Muetze42** [comment]
All OK. For all other....
Edit resources/js/components/FormField.vue
```
        initialRow: {
          id: 0,
          type: 'video',
          value: ''
        },
```

**Comment by GuillaumeFerron** [comment]
Thanks for the feedback @NormanHuth, making the initial row to be modular is part of the Roadmap, I'll keep you posted when I get around it
