### ISSUE TITLE
Problem mit Youtube Playlist.

### ISSUE THREAD

**Issue by Muetze42** [GuillaumeFerron/post-content#6]
If you copy a Youtube link from a playlist ID, the video will not work.

**Comment by GuillaumeFerron** [comment]
Hi @NormanHuth,

I pushed a version v1.1.0 that should take care of properly sanitizing the youtube URL. I would advise to use regular youtube URLs in general for Youtube based modules.

https://github.com/GuillaumeFerron/post-content/releases/tag/1.1.0

Let me know if that worked for you.

Closing this issue
